Add runbook
Financial-Times/public-suggestions-api pull request #31
Opened 2020-12-10 05:31 UTC by mchompalova

# Description

## What

Add runbook for the service.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-1181

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2020-12-10 07:42 UTC, bboykov submitted a review, later dismissed

2020-12-10 08:12 UTC, bboykov approved these changes

2020-12-10 08:37 UTC, bboykov submitted a review, later dismissed

2020-12-10 09:29 UTC, karsov requested changes
I was surprised that there are a lot more changes in this PR other than a runbook.

I have reviewed the runbook only for the moment.

2020-12-10 09:29 UTC, karsov commented on runbooks/runbook.md
> +- <https://upp-prod-delivery-us.upp.ft.com/__health>
In other services we provide direct links to the service healthchecks.

2020-12-10 09:29 UTC, karsov commented on runbooks/runbook.md
> +The service is deployed in the delivery clusters.
In other runbooks here we have a link to the failover docs.

2020-12-10 09:29 UTC, karsov commented on runbooks/runbook.md
> +# UPP - Public Suggestions API
The dependences are missing. Some (not all) of them a listed in the current runbook.

2020-12-10 09:29 UTC, karsov commented on runbooks/runbook.md
> +<https://github.com/Financial-Times/public-suggestions-api>
The service has a public URL. It is referenced in the current runbook.

2021-01-04 09:15 UTC, bboykov submitted a review, later dismissed

2021-01-08 15:04 UTC, bboykov approved these changes

2021-01-08 15:10 UTC, karsov requested changes
Let's separate the runbook in another PR.
I don't have enough context for the code changes and also they look problematic to me.

2021-01-08 15:10 UTC, karsov commented on service/conceptFilter.go
> +	refreshing  bool
This property is not used.

2021-01-08 15:10 UTC, karsov commented on service/conceptFilter.go
> +	defer f.uuidsMx.Unlock()
This means that during the whole HTTP request `IsConceptAllowed ` will be blocked and wait for the cache refresh.

2021-01-18 09:07 UTC, ekaneva reviewed
Please rename this PR as it is misleading. The runbook was already approved and merged through a separate PR. This one consist of changes that should be reviewed within the Metadata team in my opinion.

2021-01-21 09:48 UTC, closed without merging